# Generated by Django 6.0.3 on 2026-04-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='temporary_password',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
