# Generated by Django 6.0.3 on 2026-04-11 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_userprofile_temporary_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='prices.snapshot'),
        ),
    ]
