# Generated by Django 6.0.3 on 2026-04-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0004_price_snapshot_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='status',
            field=models.CharField(choices=[('downloading', 'Downloading'), ('processing', 'Processing'), ('processed', 'Processed'), ('error', 'Error')], default='downloading', max_length=16),
        ),
    ]
