# Generated by Django 6.0.3 on 2026-04-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0006_analysis_run_automatically'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='max_snapshots',
            field=models.PositiveIntegerField(default=100, help_text='Maximum number of snapshots to display in pivot tables.'),
        ),
    ]
