# Generated by Django 6.0.4 on 2026-04-19 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0007_analysis_max_snapshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTransferTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('export', 'Export'), ('import', 'Import')], max_length=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=10)),
                ('file_path', models.CharField(blank=True, default='', max_length=512)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_tasks', to='prices.analysis')),
            ],
        ),
    ]
