# Generated by Django 6.0.3 on 2026-04-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0008_analysistransfertask'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkedUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('filename', models.CharField(max_length=256)),
                ('total_chunks', models.PositiveIntegerField()),
                ('received_chunks', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('error', 'Error')], default='in_progress', max_length=20)),
                ('temp_dir', models.CharField(max_length=512)),
                ('final_path', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
