# Generated by Django 6.0.3 on 2026-04-23 03:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0012_snapshot_price_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistransfertask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('error', 'Error')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
