# Generated by Django 6.0.4 on 2026-04-08 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_inspectioncache_duration_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_interval_minutes', models.PositiveIntegerField(blank=True, help_text='Durée entre les inspections automatiques (en minutes). Laissez vide pour utiliser la valeur par défaut du .env.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('manual_inspection_enabled', models.BooleanField(default=False, help_text="Activer le mode d'inspection manuel (désactive les inspections automatiques).")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
    ]
